version: 2

project_name: ccb

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: ccb
    main: ./cmd/ccb/
    binary: ccb
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - bin/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999

release:
  github:
    owner: anthropics
    name: claude_code_bridge
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## CCB v{{.Version}}

    Claude Code Bridge - Multi-model AI collaboration tool
  footer: |
    **Full Changelog**: https://github.com/anthropics/claude_code_bridge/compare/{{ .PreviousTag }}...{{ .Tag }}
